apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: db-connection
  namespace: ferrea-libraries
stringData:
  DB_USR: neo4j
  DB_PWD: myReallyStrongPassword
  DB_URL: neo4j+s://myInstance.databases.neo4j.io
