openapi: 3.0.0

info:
  title: Libraries API
  description: API that handles the libraries registered to Ferrea circuit.
  version: 1.0.0
  contact:
    "name": "Eugenio Grimoldi"
    "url": "https://github.com/Grimoldi/ferrea-libraries"

paths: !include paths.yaml

components:
  responses: !include responses.yaml

  schemas: !include schemas.yaml

tags: !include tags.yaml
